### PR TITLE
Bump CMake requirement to the minimum version required by Zeek

### PR DESCRIPTION
**Pull request by bbannier**
Zeek changed its minimum required CMake version to 3.15.0 sometimes in the last year, and to build against Zeek's CMake setup requires using at least the same if not newer version in downstream projects.

### CODE REVIEW

**Comment by bbannier** [comment]
The instructions were unclear on how to install nmap development headers, so I was not able to test a full build; this PR gets over a CMake version check which would fail a configure run before that though.

**Review by awelzel — APPROVED** [review]

**Comment by awelzel** [comment]
> The instructions were unclear on how to install nmap development headers, so I was not able to test a full build; this PR gets over a CMake version check which would fail a configure run before that though.

Would be easiest to test on FreeBSD.

**Comment by bbannier** [comment]
I merged this, but for this to become available for `zkg install zeek-netmap` this still needs a version bump which I am unsure about due to other changes.

To install the development version one can use

```console
$ zkg install zeek-netmap  --version=master
```

* * *
**EDIT**: This is part of the latest release of this plugin 2.0.1.

**Comment by clopmz** [comment]
I have tested in a new FreeBSD host and output is:

The following packages will be INSTALLED:
  zeek/zeek/zeek-netmap (master)

Proceed? [Y/n]
"zeek/zeek/zeek-netmap" requires a "netmap_root_dir" value (Root directory of Netmap installation):
netmap_root_dir:
Saved answers to config file: /opt/zeek/etc/zkg/config
Running unit tests for "zeek/zeek/zeek-netmap"
2024-09-08 08:00:02 WARNING  installing "zeek/zeek/zeek-netmap": no __load__.zeek in implicit script_dir, skipped installing scripts
Installing "zeek/zeek/zeek-netmap"........2024-09-08 08:00:12 WARNING  installing "zeek/zeek/zeek-netmap": no __load__.zeek in implicit script_dir, skipped installing scripts

Installed "zeek/zeek/zeek-netmap" (master)

**Comment by timwoj** [comment]
> "zeek/zeek/zeek-netmap" requires a "netmap_root_dir" value (Root directory of Netmap installation):
> netmap_root_dir:

For this part, we could add some indication that this is optional. The cmake code will look in /usr and /usr/local for the header if you don't provide one, so it's just noisy for the user.

> 2024-09-08 08:00:02 WARNING installing "zeek/zeek/zeek-netmap": no load.zeek in implicit script_dir, skipped installing scripts
> Installing "zeek/zeek/zeek-netmap"........2024-09-08 08:00:12 WARNING installing "zeek/zeek/zeek-netmap": no load.zeek in implicit script_dir, skipped installing scripts

This part is somewhat surprising that we even warn about it. If there aren't scripts to install, why warn about not being able to install scripts? Pinging @ckreibich for thoughts.

**Pull request merged**
